name: Test

on:
  push:
  pull_request:
  workflow_call:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        db-version: [2]
        node-version: [16.x, 18.x]

    steps:
      - uses: actions/checkout@v3

      - name: Setup NodeJS ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install NodeJS dependencies
        run: "npm ci"

      - name: Setup EdgeDB ${{ matrix.db-version }}
        uses: edgedb/setup-edgedb@v1
        with:
          server-version: ${{ matrix.db-version }}

      - name: Run tests
        run: "npm run test"
